import React, { useState } from 'react';
import './style.css';
import './style2.css';
import { ChevronLeft, ChevronRight, X } from "lucide-react";
import nafuu1 from "./images/nafuu/1 - landing page.png";
import nafuu2 from "./images/nafuu/2 - login page.png";
import nafuu3 from "./images/nafuu/3 - dashboard showing user stats.png";
import nafuu4 from "./images/nafuu/4 - enabling user data input.png";
import nafuu5 from "./images/nafuu/5- user patient autogenerated report.png";
import nafuu6 from "./images/nafuu/6 - user appointments calendar.png";
import nafuu7 from "./images/nafuu/7 - video chat enabled.png";
import nafuu8 from "./images/nafuu/8 - settings page.png";
import viewNyumba1 from "./images/viewNyumba/home page.png";
import viewNyumba12 from "./images/viewNyumba/home page 2.png";
import viewNyumba13 from "./images/viewNyumba/home page 3.png";
import viewNyumba2 from "./images/viewNyumba/listings page.png";
import viewNyumba3 from "./images/viewNyumba/user-dashboard.png";
import readinglist from "./images/reading-list.png";
import nutripedia from "./images/nutripedia.PNG";
import ecom1 from "./images/ecommerce-site/ecom1.PNG";
import ecom2 from "./images/ecommerce-site/ecom2.PNG";
import ecom3 from "./images/ecommerce-site/ecom3.PNG";
import ecom4 from "./images/ecommerce-site/ecom4.PNG";
import ecom5 from "./images/ecommerce-site/ecom5.png";


function Projects() {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [modalOpen, setModalOpen] = useState(false);
  const [selectedProject, setSelectedProject] = useState(null);
  const [currentImageIndex, setCurrentImageIndex] = useState(0);

 const projects = [
  {
    id: 'project1',
    category: 'Real Estate',
    images: [viewNyumba1, viewNyumba12, viewNyumba13, viewNyumba2, viewNyumba3],
    description: 'A personalized real estate catalog with premium access to property information',
    alt: 'View Nyumba'
  },
  {
    id: 'project2',
    category: 'Ecommerce',
    images: [ecom1, ecom2, ecom3, ecom4, ecom5],
    description: 'An e-commerce website with product catalogues, for the user to add to cart, order and pay through       M-pesa',
    alt: 'E-shop'
  },
  {
    id: 'project3',
    category: 'Literature',
    images: [readinglist],
    description: 'An app designed for users to manage their reading interests. It allows users to search for books, add them to a personal reading list, and remove them as needed.',
    alt: 'Reading List'
  },
  {
    id: 'project4',
    category: 'Nutrition',
    images: [nutripedia],
    description: 'A food nutritional facts reference catalogue. It shows the quantity of nutrients (carbohydrates., fat, protein) per serving of various food items',
    alt: 'Nutripedia'
  },
  {
    id: 'project5',
    category: 'Healthcare',
    images: [nafuu1, nafuu2, nafuu3, nafuu4, nafuu5, nafuu6, nafuu7, nafuu8],
    description: 'Mobile Healthcare platform with progress tracking and risk prediction',
    alt: 'Nafuu'
  }
];


  const handlePrev = () => {
    setCurrentIndex((prevIndex) => 
      prevIndex === 0 ? projects.length - 1 : prevIndex - 1
    );
  };

  const handleNext = () => {
    setCurrentIndex((prevIndex) => 
      prevIndex === projects.length - 1 ? 0 : prevIndex + 1
    );
  };

  const openModal = (project) => {
    setSelectedProject(project);
    setCurrentImageIndex(0);
    setModalOpen(true);
  };

  const closeModal = () => {
    setModalOpen(false);
    setSelectedProject(null);
    setCurrentImageIndex(0);
  };

  const handleModalImagePrev = () => {
    setCurrentImageIndex((prevIndex) => 
      prevIndex === 0 ? selectedProject.images.length - 1 : prevIndex - 1
    );
  };

  const handleModalImageNext = () => {
    setCurrentImageIndex((prevIndex) => 
      prevIndex === selectedProject.images.length - 1 ? 0 : prevIndex + 1
    );
  };

  return (
    <>
      <div className='slide-title'></div>
      <h1 className='projects-header-text'>My Projects</h1>

      <div className="category-buttons">
        {projects.map((project, index) => (
          <button
            key={project.id}
            className={`category-button ${index === currentIndex ? 'active' : ''}`}
            onClick={() => setCurrentIndex(index)}
          >
            {project.category}
          </button>
        ))}
      </div>

      <section className="all-projects">
        <div className="carousel-container">
          <button 
            className="carousel-control prev" 
            onClick={handlePrev}
            aria-label="Previous project"
          >
            <ChevronLeft size={24} />
          </button>
          
          <div className="projects-list">
            {projects.map((project, index) => (
              <div 
                key={project.id}
                className={`project-item ${index === currentIndex ? 'active' : ''}`}
                onClick={() => openModal(project)}
                role="button"
                tabIndex={0}
                aria-label={`View details for ${project.alt}`}
              >
                <div className="list-card">
                  <img 
                    src={project.images[0]}
                    alt={project.alt}
                    className="project-image"
                  />
                  <div className="short-description">
                    <h2><b>{project.alt}</b></h2>
                    <p>{project.description}</p>
                     <button className="see-more-btn">See More</button>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <button 
            className="carousel-control next" 
            onClick={handleNext}
            aria-label="Next project"
          >
            <ChevronRight size={24} />
          </button>
        </div>
      </section>

      {modalOpen && selectedProject && (
        <div className={`modal-overlay ${modalOpen ? 'open' : ''}`}>
          <div className="modal-content">
            <button 
              className="modal-close" 
              onClick={closeModal}
              aria-label="Close modal"
            >
              <X size={24} />
            </button>
            <div className="modal-carousel">
              <button 
                className="modal-control prev" 
                onClick={handleModalImagePrev}
                aria-label="Previous image"
              >
                <ChevronLeft size={24} />
              </button>
              <div className="modal-image-container">
                {selectedProject.images.map((image, index) => (
                  <img 
                    key={index}
                    src={image}
                    alt={`${selectedProject.alt} ${index + 1}`}
                    className={`modal-image ${index === currentImageIndex ? 'active' : ''}`}
                  />
                ))}
              </div>
              <button 
                className="modal-control next" 
                onClick={handleModalImageNext}
                aria-label="Next image"
              >
                <ChevronRight size={24} />
              </button>
            </div>
            <div className="modal-description">
                <h2>{selectedProject.alt}</h2>
                <p>{selectedProject.description}</p>

                {selectedProject.site && (
                  <a
                    href={selectedProject.site}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="btn visit-site-button"
                  >
                    Visit Site
                  </a>
                )}
              </div>

          </div>
        </div>
      )}
    </>
  );
}

export default Projects;